# -*- coding: utf-8 -*-
"""sentiment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IrWtABvaWWtUZNANCcW08HO6wC4-kKSU
"""

import pandas as pd
import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification
from torch.nn.functional import softmax

# Load the pre-trained model and tokenizer
tokenizer = AutoTokenizer.from_pretrained("LiYuan/amazon-review-sentiment-analysis")
model = AutoModelForSequenceClassification.from_pretrained("LiYuan/amazon-review-sentiment-analysis")

# Check if CUDA is available and move model to GPU if possible
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")
model = model.to(device)

# Load your Amazon Handmade dataset
df = pd.read_csv('/content/amazon_handmade_train.csv')
df.head()

# Function to predict sentiment and map to your annotation scheme
def predict_usefulness(review_text):
    # Handle empty reviews
    if pd.isna(review_text) or review_text.strip() == '':
        return 0  # Consider empty reviews as useless

    # Tokenize the review
    inputs = tokenizer(review_text, return_tensors="pt", truncation=True, max_length=512, padding=True)

    # Move inputs to the same device as the model
    inputs = {key: val.to(device) for key, val in inputs.items()}

    # Make prediction
    with torch.no_grad():
        outputs = model(**inputs)
        predictions = softmax(outputs.logits, dim=-1)

    # Get the predicted class (0: negative, 1: positive)
    predicted_class = torch.argmax(predictions, dim=-1).item()

    # Map the sentiment to your annotation scheme (1: useful, 0: useless)
    return predicted_class

# Process in batches for better GPU utilization
from tqdm import trange
batch_size = 32  # Adjust based on your GPU memory
results = []

for i in trange(0, len(df), batch_size):
    # print(f"Processing reviews {i} to {min(i+batch_size, len(df))}")
    batch = df.iloc[i:i+batch_size]

    # Process reviews in the current batch
    batch_labels = [predict_usefulness(review) for review in batch['review_text']]
    results.extend(batch_labels)

# Add labels to the dataframe
df['label'] = results

# Save the annotated dataset
df.to_csv('amazon_handmade_annotated.csv', index=False)

df['label'].value_counts()

